import mongoose from "mongoose"

const questionSchema = new mongoose.Schema({
  // The question text
  question: { type: String, required: true },
  // Type of question (e.g., 'MCQ', 'Coding')
  type: { type: String, required: true },
  // Reference to the round this question belongs to
  roundname: { type: mongoose.Schema.Types.ObjectId, ref: "Round", required: true },
  // Difficulty level (e.g., 'Easy', 'Medium', 'Hard')
  difficulty: { type: String },
  // Array of options (for MCQ type)
  options: { type: [String] },
  // The correct answer
  correctAnswer: { type: String },
  // Whether the question was generated by AI
  isAIGenerated: { type: Boolean, default: false },
  // Any additional metadata
  metadata: { type: mongoose.Schema.Types.Mixed },
}, { timestamps: true })

const Question = mongoose.models.Question || mongoose.model("Question", questionSchema)

export default Question
